CREATE TABLE [dbo].[ExceptionLog] (
    [LogID]             INT             IDENTITY (1, 1) NOT NULL,
    [Priority]          INT             NOT NULL,
    [Severity]          NVARCHAR (32)   NOT NULL,
    [Title]             NVARCHAR (256)  NOT NULL,
    [Timestamp]         DATETIME        NOT NULL,
    [MachineName]       NVARCHAR (32)   NOT NULL,
    [AppDomainName]     NVARCHAR (256)  NOT NULL,
    [ProcessID]         NVARCHAR (256)  NOT NULL,
    [ProcessName]       NVARCHAR (256)  NOT NULL,
    [ThreadName]        NVARCHAR (256)  NULL,
    [Win32ThreadId]     NVARCHAR (128)  NULL,
    [Type]              NVARCHAR (150)  NULL,
    [Message]           NVARCHAR (4000) NULL,
    [Source]            NVARCHAR (64)   NULL,
    [TargetSite]        NVARCHAR (128)  NULL,
    [StackTrace]        NVARCHAR (MAX)  NULL,
    [ThreadIdentity]    NVARCHAR (64)   NULL,
    [InnerExceptions]   NVARCHAR (MAX)  NULL,
    [SessionId]         NVARCHAR (512)  NULL,
    [UsersessionId]     NVARCHAR (256)  NULL,
    [UserIdentifier]    NVARCHAR (256)  NULL,
    [ApplicationName]   NVARCHAR (256)  NULL,
    [ContextIdentifier] NVARCHAR (128)  NULL,
    [IpAddress]         NVARCHAR (256)  NULL,
	[TracingToken]      UNIQUEIDENTIFIER NULL
);

