CREATE TABLE [dbo].[Log] (
    [LogID]             INT              IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Priority]          INT              NOT NULL,
    [Severity]          NVARCHAR (32)    NOT NULL,
    [Title]             NVARCHAR (256)   NOT NULL,
    [Timestamp]         DATETIME         NOT NULL,
    [MachineName]       NVARCHAR (32)    NOT NULL,
    [AppDomainName]     NVARCHAR (512)   NOT NULL,
    [ProcessID]         NVARCHAR (256)   NOT NULL,
    [ProcessName]       NVARCHAR (512)   NOT NULL,
    [ThreadName]        NVARCHAR (512)   NULL,
    [Win32ThreadId]     NVARCHAR (128)   NULL,
    [Message]           NVARCHAR (2048)  NULL,
    [SessionId]         UNIQUEIDENTIFIER NULL,
    [CallType]          NVARCHAR (128)    NULL,
    [ProviderId]        INT              NULL,
    [Status]            NVARCHAR (32)    NULL,
    [TimeTaken]         FLOAT            NULL,
    [UsersessionId]     NVARCHAR (256)   NULL,
    [UserIdentifier]    NVARCHAR (256)   NULL,
    [ApplicationName]   NVARCHAR (256)   NULL,
    [ContextIdentifier] NVARCHAR (128)   NULL,
    [IpAddress]         NVARCHAR (256)   NULL,
	[TracingToken]      UNIQUEIDENTIFIER NULL
);

