CREATE FUNCTION [dbo].[fnHash] (@data VARCHAR(200)) RETURNS VARCHAR(max)
WITH SCHEMABINDING, RETURNS NULL ON NULL INPUT
BEGIN
RETURN ( SELECT [text()] = HashBytes('SHA1', @data)  FOR XML PATH('') )
END