ALTER TABLE [dbo].[ExceptionData]
    ADD CONSTRAINT [PK_ExceptionData] PRIMARY KEY CLUSTERED ([LogId] ASC, [Key] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

